<?php
    exec('fswebcam -d v4l2:/dev/video0 img/out01.jpg');
    exec('sh /home/pi/usbreset.sh');
    exec('fswebcam -d v4l2:/dev/video0 img/out02.jpg');
    exec('sh /home/pi/usbreset.sh');
    exec('fswebcam -d v4l2:/dev/video0 img/out03.jpg');
    exec('sh /home/pi/usbreset.sh');
    exec('fswebcam -d v4l2:/dev/video0 img/out04.jpg');
    exec('sh /home/pi/usbreset.sh');
    exec('fswebcam -d v4l2:/dev/video0 img/out05.jpg');
    exec('sh /home/pi/usbreset.sh');
    exec('fswebcam -d v4l2:/dev/video0 img/out06.jpg');
    exec('sh /home/pi/usbreset.sh');
    exec('fswebcam -d v4l2:/dev/video0 img/out07.jpg');
    exec('sh /home/pi/usbreset.sh');
    exec('fswebcam -d v4l2:/dev/video0 img/out08.jpg');
    exec('sh /home/pi/usbreset.sh');
    exec('fswebcam -d v4l2:/dev/video0 img/out09.jpg');
    exec('sh /home/pi/usbreset.sh');
    exec('fswebcam -d v4l2:/dev/video0 img/out10.jpg');
    exec('sh /home/pi/usbreset.sh');
    exec('fswebcam -d v4l2:/dev/video0 img/out11.jpg');
    exec('sh /home/pi/usbreset.sh');
    exec('fswebcam -d v4l2:/dev/video0 img/out12.jpg');
    exec('sh /home/pi/usbreset.sh');
    exec('fswebcam -d v4l2:/dev/video0 img/out13.jpg');
    exec('sh /home/pi/usbreset.sh');
    exec('fswebcam -d v4l2:/dev/video0 img/out14.jpg');
    exec('sh /home/pi/usbreset.sh');
    exec('fswebcam -d v4l2:/dev/video0 img/out15.jpg');
    exec('sh /home/pi/usbreset.sh');
    exec('fswebcam -d v4l2:/dev/video0 img/out16.jpg');
    exec('sh /home/pi/usbreset.sh');
    exec('fswebcam -d v4l2:/dev/video0 img/out17.jpg');
    exec('sh /home/pi/usbreset.sh');
    exec('fswebcam -d v4l2:/dev/video0 img/out18.jpg');
    exec('sh /home/pi/usbreset.sh');
    exec('fswebcam -d v4l2:/dev/video0 img/out19.jpg');
    exec('sh /home/pi/usbreset.sh');
    exec('fswebcam -d v4l2:/dev/video0 img/out20.jpg');
    exec('sh /home/pi/usbreset.sh');
